### ISSUE TITLE
如何使用这个Taoba-Grub

### ISSUE THREAD

**Issue by McChickenNuggets** [MskAdr/Tao-Ba-Grub#1]
我尝试运行了一下，发现没有产生任何结果。
我看了看，没有找到主函数，不知道咋运行。

**Comment by McChickenNuggets** [comment]
![image](https://user-images.githubusercontent.com/54528469/100623018-89fd0380-335c-11eb-94c2-e12752051789.png)
这些函数咋都没有调用呢？

**Comment by MskAdr** [comment]
抱歉刚看到，你就把这当成一个库就行，没有主函数调用的，拷贝到你的程序里面，需要的时候直接调用就行。
